### ISSUE TITLE
Build container images for linux/arm64 too

### ISSUE THREAD

**Issue by FastestMolasses** [LAION-AI/Open-Assistant#1010]
Trying to run the docker containers on a raspberry pi, however the existing images do not support the linux/arm64 architecture.

**Comment by cooph2022** [comment]
> Trying to run the docker containers on a raspberry pi, however the existing images do not support the linux/arm64 architecture.

What resources are really required to run this?

**Comment by occupytheweb** [comment]
@FastestMolasses the official images such as [redis](https://hub.docker.com/layers/library/redis/latest/images/sha256-3158710be29203a78b8729e1cc69b2312dc3e6ced668a24b196e929f5396046f?context=explore), [postgres](https://hub.docker.com/layers/library/postgres/latest/images/sha256-0371d78f79e0a43fe47160a5a61a6b9fc84dec160f3805b357016a013ee119f5?context=explore), [maildev](https://hub.docker.com/layers/maildev/maildev/latest/images/sha256-ee29d9d960b97ab8418238d4a9ac4cf9ad958280d02f219d81fbb7720db197cc?context=explore) are already multi-arch.

Is the `oasst-postgres` image the one causing an issue? You can replace it by plain `postgres`.

For the other images, can you try building them with
```shell
docker buildx bake -f docker-compose.yaml --set '*.platform=linux/arm64'
```

or

```shell
export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1
export DOCKER_DEFAULT_PLATFORM=linux/arm64

docker compose build
```
?

**Comment by GuilleHoardings** [comment]
I also tried to develop in a raspberry pi, but in a raspberry pi 3 (arm/v7), and had problems with the images. I've detected that at least these images give problems:

- `ghcr.io/laion-ai/open-assistant/oasst-postgres`
- `redislabs/redisinsight:latest`
- `oasst-backend`, which uses `Dockerfile.backend`, which is based on `tiangolo/uvicorn-gunicorn-fastapi`, which is only available for amd64

Using `docker buildx` as suggested above doesn't work because some of these images don't have an arm64 version available.

**Comment by fozziethebeat** [comment]
Given that we depend on postgres and redis, it's not clear if rasberry pi will be easy to support.  What's the key use case for running everything on rasberry pi?

**Comment by GuilleHoardings** [comment]
My use case is that I would like to develop on a Raspberry Pi that I have. For translating the website, which is basically what I'm doing now, I think the Raspberry Pi should be able to handle it.

Anyway, I don't know if many people are in the same situation as me, so maybe it's not important...
