### ISSUE TITLE
Being able to review your own replies

### ISSUE THREAD

**Issue by HugoVG** [LAION-AI/Open-Assistant#1014]
In the current implementation you are able to review your own answers/replies, i don't think this is a great thing because people can use it to give garbage replies and review them as really good 
![image](https://user-images.githubusercontent.com/64896329/215499930-8ad5d908-6d71-490e-9010-2bd56a4054e0.png)

**Comment by andreaskoepf** [comment]
Was the highlighted message written by you or only earlier messages in the conversation? The system should not allow you to label your own messages but if your messages are parents of other user's replies they can show up.

**Comment by HugoVG** [comment]
the highlighted message was from me.

**Comment by andreaskoepf** [comment]
> the highlighted message was from me.

OK, right now I don't know how this is possible since we filter based on the user id and the self-labeling option is off for the production instance.

https://github.com/LAION-AI/Open-Assistant/blob/091e93392bef64f51234fcdf2902463a0585bdac/backend/oasst_backend/tree_manager.py#L842-L843

I will add a test at a different location that will raise an exception if this happens. This might help us to identify under which circumstances this occurs.
