### ISSUE TITLE
Implement critical admin functions

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#1022]
We need Admin UI for the following functions (**only displayed for admin users**): 

- [x] User-Id link in every message that navigates to the admin user-page of the author (e.g. to disable a user, inspect message history) (resolved via https://github.com/LAION-AI/Open-Assistant/pull/1021)
- [x] "delete message" command for all messages (e.g. in "..." drop down) -> call `DELETE` `/api/v1/messages/{message-id}` ..
- [x] "stop tree" command in all messages (set them into halted-by-moderator state) (e.g. in "..." drop down) (backend function to halt tree added by: https://github.com/LAION-AI/Open-Assistant/pull/1025)
- [ ] browse through all the user's messages (not just last 10, e.g. user message cursor endpoint)
- [ ] browse all message trees of the system (e.g. via general message cursor endpoint, only roots first and then view the whole message tree)

**Comment by rjmacarthy** [comment]
I have opened a PR for point number 1.

**Comment by kingychiu** [comment]
I am looking at the 4th point here `browse through all the user's messages (not just last 10, e.g. user message cursor endpoint)`

The current state of this page is to have the latest 10 messages of a user, but the UI is showing the latest message at the top. Is it expected behavior?

![Image](https://user-images.githubusercontent.com/11500136/216825753-24d886c7-bcb9-46c4-ad16-e33664d6365b.png)


About the pagination/cursor feature here. I am thinking of having a button `Load older message" to load 10 more old messages at the top/bottom depending on the answer of the question above.

**Comment by notmd** [comment]
@kingychiu have you start the work?

**Comment by kingychiu** [comment]
@notmd  Not yet

**Comment by notmd** [comment]
I think this can be closed now
