### ISSUE TITLE
What does PII mean?

### ISSUE THREAD

**Issue by ClashLuke** [LAION-AI/Open-Assistant#1039]
When working with the [label prompter](https://open-assistant.io/label/label_prompter_reply), there are a couple of flags people can choose from to mark data:
![image](https://user-images.githubusercontent.com/39779310/215773826-4c735c43-e2da-4dda-9255-f6b026c1ec6c.png)

While most are self-explanatory or use common phrases, I've never heard of "PII" before. Would it be possible to expand the abbreviation or explain its meaning in a tooltip?

**Comment by andreaskoepf** [comment]
It stands for personally identifiable information (PII), see https://en.wikipedia.org/wiki/Personal_data

"The abbreviation PII is widely accepted in the [United States](https://en.wikipedia.org/wiki/United_States), but the phrase it abbreviates has four common variants based on personal or personally, and identifiable or identifying." ;-)

But maybe we need to make this clearer or add at least a tooltip.

**Comment by kevindamm** [comment]
Some help text might make this clearer, or maybe if "contains PII" is selected, a description and requiring the user to acknowledge understanding.  It's difficult to convey in a tooltip because the concept isn't easy to summarize briefly.

NIST definition is "any information about an individual maintained by an agency, including (1) any information that can be used to distinguish or trace an individual's identity, such as name, social security number, date and place of birth, mother's maiden name, or biometric records; and (2) any other information that is linked or linkable to an individual, such as medical, educational, financial, and employment information."  So an IP address is not PII by itself, but is linked PII and many people would consider it PII especially in certain circumstances.  Physical address (or home mailing address) is technically not PII nor linked PII but I would be more worried about that being leaked than my name or date of birth.

I feel like it's definitely an important feature to label, though.

**Comment by fozziethebeat** [comment]
I think it's worth adding a [Chakra Tooltip](https://chakra-ui.com/docs/components/tooltip) for each of these labels that have additional explanatory text.

If anyone wants to tackle this, please post and I'll assign it to you

**Comment by othrayte** [comment]
I'll quickly do this one, I've been meaning to add descriptions since changing them to buttons anyway.
