### ISSUE TITLE
Allow a user to link their Discord account after registering with email

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#106]
NextAuthJS makes this a little hard.  Ideally a user should be able to sign up via email and then at some later date link in their Discord account.  This should update the website's account database with those discord credentials so we can then associate their contributions with their discord id from that point on.

I'm not 100% sure how to do this so if anyone wants to dive deep into NextAuthJS and figure this out (or do something a little custom that fits within NextAuthJS) that'll be a big help.

**Comment by poipiii** [comment]
I decided to do a bit of digging and turns out it’s actually quite a hassle to implement multi-provider logins for nextauth as seen in this discussion [Multiple accounts with same mail handling #2808]( https://github.com/nextauthjs/next-auth/discussions/2808)

To get it to work the user must use the same email for both open assistant and discord and enable `allowDangerousEmailAccountLinking: true` in the provider configuration as seen in the docs [here](https://next-auth.js.org/configuration/providers/oauth#allowdangerousemailaccountlinking-option) and [here ](https://github.com/nextauthjs/next-auth/blob/0ea9ada3a986ba65f07a97b768ce78785cac18af/docs/docs/reference/04-providers/02-oauth.mdx)

based on the docs I assume it should look something like this in our [[..nextauth.ts]](https://github.com/LAION-AI/Open-Assistant/blob/main/website/src/pages/api/auth/%5B...nextauth%5D.ts)
```ts
 providers.push(
    DiscordProvider({
      clientId: process.env.DISCORD_CLIENT_ID,
      clientSecret: process.env.DISCORD_CLIENT_SECRET,
      allowDangerousEmailAccountLinking: true
    })
  );
}
```

**Comment by fozziethebeat** [comment]
Sure, I haven't seen a PR for this yet so it's open for someone to look at

**Comment by callum-gander** [comment]
Got held up this weekend, going to do this tonight, sorry for the delay

**Comment by callum-gander** [comment]
Unassigned myself, I ran into errors when I tried to do this, not sure why and I don't have time to debug. Apologies, should have unassigned myself from this earlier

**Comment by fozziethebeat** [comment]
No worries, I'm actually going to close this as we're changing how auth works and will fix it via that update.
