### ISSUE TITLE
dependency failed to start: container for service "webdb" is unhealthy

### ISSUE THREAD

**Issue by akarshghale** [LAION-AI/Open-Assistant#1119]
Getting this error after the after a long time of booting. 

Running on Ubuntu 20.04 Python version 3.8. Intel i3 8gb RAM.

**Comment by olliestanley** [comment]
This might not be your issue, but in general you need Python 3.10.

**Comment by bitplane** [comment]
If it's just timing out while starting the services due to RAM or CPU contention, try increasing the timeout and retry values here:

https://github.com/LAION-AI/Open-Assistant/blob/dcb9dfe952fb0fa6fc11c719c6fc2881de19b29b/docker-compose.yaml#L34

If that's the issue and you find sensible defaults that work on your hardware please submit them as a pull request :)
