### ISSUE TITLE
Suggestion for documentation and issue creation

### ISSUE THREAD

**Issue by jasonmhead** [LAION-AI/Open-Assistant#117]
It could be good to include some base suggested reading for tasks for people who aren't familiar with the frameworks being used.

Perhaps when a task is created a link to some documentation that would help point someone in the right direction to complete the task.

I know the project is evolving and there isn't wiki content/other documentation on code structure for the code base, but some minimal links to resources on the web could be helpful in getting some people upto speed.

**Comment by fozziethebeat** [comment]
I like this idea.  I've tried to do this on the webside.

Are there specific READMEs that felt incomplete?  It'd be helpful to list specific docs we should update and enhance.

**Comment by MalikMAlna** [comment]
I'd be down to copyedit work on this one as well, but yeah we should have some examples of specific md and docs where it would make sense to create would be helpful. Honestly, an epic on setting up a wiki would probably be good too.

**Comment by andreaskoepf** [comment]
sry, misread this as it is more general about documentation. I still close it because it is too vague, the project evolved since end of December. If you feel a specific page is the documentation or important information regarding the development-setup is missing please feel free to open a separate issue.
