### ISSUE TITLE
Unknown flag: --build

### ISSUE THREAD

**Issue by Foxy6670** [LAION-AI/Open-Assistant#1179]
I tried running the command shown in the README to run the demo, `docker compose up --build`, but then I get this error:
```
unknown flag: --build
```
Keep in mind I'm using the rootless version of Docker, as to avoid using `systemd`.

**Comment by ov64556546** [comment]
Try Installing `docker-compose` package

**Comment by laudanum123** [comment]
for me it also works when I do not add --build to the command

**Comment by GuilleHoardings** [comment]
It's because you are using docker-compose v1 and you have to move to docker compose v2. See [here in the faq](https://projects.laion.ai/Open-Assistant/docs/faq#docker-compose-instead-of-docker-compose). The linked [Stack Overflow answer](https://stackoverflow.com/a/66516826) gives the fix. In short, you have to install the `docker-compose-plugin`, i.e., `apt-get install docker-compose-plugin` on Debian/Ubuntu.

**Comment by olliestanley** [comment]
Closing this as it seems to have been answered, feel free to comment again if the solutions mentioned don't work

**Comment by ShonazarovUz** [comment]
docker compose --bulid
unknown flag: --bulidw 

why

**Comment by ShonazarovUz** [comment]
> docker compose --bulid unknown flag: --build
> 
> why
