### ISSUE TITLE
Sign in via email link - sender address misspelled

### ISSUE THREAD

**Issue by QuestForge** [LAION-AI/Open-Assistant#1191]
The sender is shown as open-**assistent**@laion.ai  - it should be assistant@

This could make it look like phishing or spam.

**Comment by andreaskoepf** [comment]
@christophschuhmann what do you say? Will we leave this as is or change it? I asked you about it two weeks ago...

**Comment by ArgiesDario** [comment]
I would like to work on this one (since it is happening to me all the time, emails go to spam due this misspelling), but I need a bit of guidance

Which should be the approach to fix this? cause I was about to do the same as @swaptr PR, but @andreaskoepf you mentioned that won't fix it, I went through the code and did not find anything else email related

Thanks

**Comment by cosmicr** [comment]
Signed up yesterday, first thing I noticed. Not a great first impression.
