### ISSUE TITLE
Let Me See All of My Contributions

### ISSUE THREAD

**Issue by Miserlou** [LAION-AI/Open-Assistant#1306]
I'd love to be able to see all of the messages I've contributed, not just the most recent ones. It's very interesting to find how people have responded to prompts I've suggested.

Really, I want to see if the young seeds I've planted have grown into healthy trees.

**Comment by blankster** [comment]
It would also have a learning effect, since you can see what was a good idea and what was a bad idea. 

The only thing that would probably be annoying: When you see mistakes in your own content that you can't change (because it's already been rated).

**Comment by Dryhb** [comment]
Also beeing able to see all the messages you rated(in general, be able to check back what you have encountered). Maybe an option to have favorites to follow a discussion because maybe you are interested in the answers or feedbacks.
Seeing everything you have encountered would be useful for debugging, if you have seen an issue with a task but didn't note the task id you could go into that task later to find it back

**Comment by andreaskoepf** [comment]
Related #1348

**Comment by johnflux** [comment]
I made a pull request for the API side of it - a request for comments:
https://github.com/LAION-AI/Open-Assistant/pull/1864

**Comment by johnflux** [comment]
How about this:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1230500/221397619-ae41ef3a-0883-48fc-96eb-7798b0eceefa.png">
