### ISSUE TITLE
Create a way to correct or flag misspellings in answers and questions in the data contribution.

### ISSUE THREAD

**Issue by javiergcim** [LAION-AI/Open-Assistant#1412]
Random, at least in Spanish. I have ended up seeing that 9 out of 10 answers have some very faulty spelling or writing. Many of them serious, and that can affect the quality of the data that will feed the final system.

**Comment by jwstolk** [comment]
Errors in questions should remain, but I agree that errors in answers should be corrected as much as possible. Both manual and automatic corrections should somehow be shown (with the changes highlighted) to other users for confirmation.
Like data entered in the wrong language, I hope we can somehow correct mistakes instead of throwing away good otherwise data.

A possible issue could be that a user specifically replied about a spelling error made in an answer, and fixing the spelling brakes that part of the thread, possibly after that different thread is already labeled. A possible solution could be to make the corrected answer with "corrected spelling" if it already has follow-up questions, and delete the reviews of those follow-up questions so the review process could detect such issues.

Also, when an answer is corrected, all existing reviews of that answer should be deleted, especially when those reviews where made when indicating spelling issues was not yet a separate label option.

**Comment by aayojezuzchrezt** [comment]
Errors in questions **must** be included. It'll let model recognize user's input later, even with misspells and errors.
Agreed about answers, should be option to provide correction for them as many good have little typos, and it's decreasing data quality.

**Comment by ParisNeo** [comment]
We can do both. Keep the misspells and have a copy with the misspels repared

**Comment by King-Darius** [comment]
[I see this topic has come up here too](https://github.com/LAION-AI/Open-Assistant/issues/1005)

**Comment by AbdBarho** [comment]
Fixed in  #3280 for moderators, we are considering to allow others to propose changes as well.
