### ISSUE TITLE
New grammar/coherence/cohesion rating

### ISSUE THREAD

**Issue by TeenebrisHV** [LAION-AI/Open-Assistant#1558]
Currently, the only way to "rate" a typo in an answer is to classify it with less quality and downvote it or report it. But what happens when there is a high-quality response, with accurate and helpful information presented that has typos?

It would be helpful to have a separate label for such occasions or even an option to correct such responses. Maybe even to add an option to rewrite it using proper grammar.

**Comment by horribleCodes** [comment]
The rewriting system is a whole other can of worms because it'd get used to correct factual errors, replies without necessary warnings and other things. But this is a dimension that is currently not considered in the data set, so it could be a good idea. Personally, I'd generalize it to "readability", and it could refer to how easy it is to read the message. Typos and poor grammar hurts readability, but so does lack of paragraphs, missing or broken Markdown syntax and poor wording.

**Comment by olliestanley** [comment]
The concern with a new label is that we have already collected a large proportion of the data, so the new label would not be present for all previously labelled messages.

**Comment by horribleCodes** [comment]
I understand, but would it be possible to allow a blank value for new labels so? Maybe somewhere down the future someone could use the later posts to complete the old datapoints with a model specialized in judging readability.

**Comment by ljleb** [comment]
I have seen multiple instaces of messages that contain typos but also that have been upvoted a lot. Isn't this going to be a huge problem for code responses quality?

I heard that training had been initiated on multiple models, is there any feedback on the quality of the format? If there is a significant impact on the format the model understands, I think this should be considered a higher priority issue, as we'll probably need to patch the dataset in some way, whether by adding new labels or updating the conversation trees.

**Comment by olliestanley** [comment]
Duplicate #1412
