### ISSUE TITLE
Classification Table Error (false positive)

### ISSUE THREAD

**Issue by dave-guzman** [LAION-AI/Open-Assistant#1591]
Since yesterday, I have noticed that the classification table on the Open Assistant website has been showing errors. Firstly, it does not show me in the table, neither in the daily nor monthly rankings, in any of the tables. Secondly, this is a problem because the table was a guide and confirmation for me to know if my contributions to the community were being sent correctly. I hope there is a solution, since in my free time I like to help make this assistant beneficial for people. My email is: daveguzman2052@gmail.com, and my username is Dave_

**Comment by olliestanley** [comment]
Hi. We previously had reports from users who were concerned your volume of messages submitted was too high to be all written by a human. We have contacted you on your email address to discuss this, please respond when you are able.

**Comment by dave-guzman** [comment]
Good afternoon,

Forgive me if I haven't responded sooner, I ended up finding Oliver's
previous message in the trash, I probably deleted it without giving it
importance.

I also apologize if I have given concerns about my activity within the page
in the last two days.

I must confess that at least 40% of my total responses have been 'prompted'
by IA's help, but, I am dedicated to carefully reviewing some of the
responses I receive from her.

I don't ask for my profile to be shown on the board again, because to be
honest, I don't care to be there, after all, they are just numbers. I just
needed his answer to know if it was a mistake or not.

I just need you to give me a confirmation as to whether I can continue to
make my replies this way, or if I have to have some moderation in doing so.
That's all I ask.

In closing, I am glad that you are on the lookout to identify this type of
suspicious activity, as I will certainly not be the first or the last.

I hope this project will be a success because I know that these kinds of
tools will be very useful to people in the future.

Have a nice day,

Dave

**Comment by olliestanley** [comment]
@dave-guzman Ok. Thanks for your contributions. We want to avoid AI-written answers, but if an AI provides information which you write into your own words that's fine. All of your messages are still coming through no problem.

**Comment by andreaskoepf** [comment]
@dave-guzman We had again to deactivate your account because you were submitting many prompts in the wrong language and other users complained about it. Someone of our moderator team will again try to get in touch with you by mail. Maybe you could get in touch with us on discord and explain a bit how you generated prompts + answers .. this might be very interesting for building a synthetic instruction tuning dataset but it is a bit problematic to have a semi-automated process collaborate with other users. I hope you understand and nevertheless thanks a lot for the many messages that you submitted.
