### ISSUE TITLE
Create a contributors / credits page

### ISSUE THREAD

**Issue by AbdBarho** [LAION-AI/Open-Assistant#1703]
This project has gathered a lot of community contributors in a very short time span.

The names of everyone who contributed should be eternalized on our app and website, with extra bells and whistles for long time team members!

**Comment by JoLalo** [comment]
Hi, I can try to help you with this. I don't know how this works regarding communications so I'll just write a comment.

**Comment by JoLalo** [comment]
Hi! Thank you for assigning me to this project. To make this easier, can I add one of you on discord to get a better understanding of what I need to do?

**Comment by bitplane** [comment]
I would guess there's several parts, which might be best done as separate tickets to keep the work nice and small

1. Developers
2. GitHub contributors
3. Data contributors (though we should ask people before exporting them)
4. Others

# Developers

Pretty easy to do in code. You can list commits by developers like this:

    git --no-pager log --format="%aN"

This would give you a list sorted by number of commits:

    git --no-pager log --format="%aN" | sort | uniq -ic | sort -nr

Dump it to a file (.gitignore it) then make a script that saves the output to a Markdown file in the docs dir. Mustache templates are pretty nice for this sort of thing, dunno if we're already using them. (`git-python` is probably nicer than using bash as above)

# GitHub contributors

Use the github API to pull user display names from all the github issues

# Contributors

A script that grabs the leaderboards from the live site and adds them into the template variables.

# Others

Probably need a special section for people who help in other ways, like compute donations, downstream models etc

# Automating it

Dunno about this. Should probably be part of the release/deploy process rather than on a commit or push hook, or maybe run it ad-hoc.

**Comment by KyleGrande** [comment]
Interested in working on this if still possible.

**Comment by AbdBarho** [comment]
@theopfr this is great! could you please create a PR with the react components? we are planning on letting team members add themselves manually to this list (instead of using the api).

**Comment by AbdBarho** [comment]
@theopfr I have a very basic page setup in #2103, the data is in the file `website/src/data/team.json`.

**Comment by theopfr** [comment]
yes sounds good, I'm updating my component now given the data in the team.json, I'm orienting it after yours, it will be very similar.

**Comment by theopfr** [comment]
okay so in the end my code does almost exactly what yours does but is probably less readable, therefore after you merged #2103 I'd just make/propose two cosmetical changes but keep yours.
