### ISSUE TITLE
Write a bot-to-backend communication test

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#180]
Write a test that spins up backend and bot, and checks whether the communication works as intended. The purpose of this is to check whether any change in the backend that we do in the future breaks the bot's assumptions about the API and about the parameters & return values.

**Comment by jack-michaud** [comment]
This issue (along with #181) could benefit from a contract test. It should test that each call satisfies the OpenAPI schema inputs and endpoints. That way, changes to the endpoint contract will automatically be caught by these tests. [FastAPI provides a function to retrieve the OpenAPI schema](https://fastapi.tiangolo.com/advanced/extending-openapi/).

Another way to test this would to hard code the response model and endpoints for these tests, but that creates more maintenance burden (when you update the endpoint, you have to remember to update the hard coded test) and a false sense of security (if you forget to update the test, tests will still pass). 

Just food for thought. Happy to take a crack at this approach if this sounds good.

**Comment by yk** [comment]
Hi @jack-michaud what would be the overhead of maintaining the contract tests? If I change the API in the backend, and change the bot's API client library accordingly such that everything works, do I also have to change something in the contract test? If not, that would be really cool and definitely a good way to go. If yes, it's a bit more tricky as it might mean big overhead.

As for database, redis, etc. I think we could use the existing docker-compose setup (there is a pytest plugin for this), and I think we already have code to create some sample data.

**Comment by jack-michaud** [comment]
> what would be the overhead of maintaining the contract tests? 

0 - Since FastAPI automatically generates the contract, any change in the API will reflect in the test. For example, changing an endpoint from '/messages/:id' to '/message/:id' in the backend code and running the tests would fail if the discord bot used the old endpoint. We would use a mock server (e.g. [Prism](https://github.com/stoplightio/prism)) to do this. 

> As for database, redis, etc. I think we could use the existing docker-compose setup (there is a pytest plugin for this), and I think we already have code to create some sample data.

Sounds like we have the infrastructure to boot up these for tests. If necessary we can dip into booting them up for testing the bot and website. This can be the shortest path to testing more complex interactions between these systems, but in my experience this creates hidden coupling between these systems. I can wax philosophical about it some more, but if I were designing this for my team I would prefer contract tests and mocking over end to end tests since that promotes well established public contracts over hidden undocumented behavior inside the API. In the long run, that means a sustainable and well thought out API surface. 

I'll start looking into contract tests, thanks @yk !

**Comment by yk** [comment]
very cool, thanks for the inputs. could you make another issue for contract tests? I can then assign it to you. we'll leave this issue for the more end-to-end kind of test

**Comment by javidlakha** [comment]
Would be happy to help on this

**Comment by andreaskoepf** [comment]
Closing all old discord bot issues. Discord data collection never took off. It might be more viable to develop a discord bot that communicates with the inference system.
