### ISSUE TITLE
"Helpful and Harmless" dataset

### ISSUE THREAD

**Issue by CheckMC** [LAION-AI/Open-Assistant#1822]
https://huggingface.co/datasets/Anthropic/hh-rlhf

Is this a dataset we could use for additional training? 

Would we need to make format changes?

**Comment by CheckMC** [comment]
https://github.com/orhonovich/unnatural-instructions

Another potential one

**Comment by ontocord** [comment]
we are already using the antrhopic dataset. thanks!

**Comment by gitcnd** [comment]
Cute, but, does anyone actually *want* this?  

Sure, the media and AI-haters pump up this concept beyond all reason, but at the end of the day - nobody really wants an AI to lie and censor on purpose - not even if they pretend they do because their job depends on keeping up that pretense...

It's like all those "accept cookies" popups blighting the web - a handful of do-gooders who think everyone else is too stupid to clear their browser cookies, forcing the entire world against their will to accept their idea of privacy... why should we be the handful who decides that everyone using our AI is too emotionally fragile to hear poor language, and to block them from asking or getting answers on abrasive topics?

**Comment by Sumanai** [comment]
Totally agree. The modern race for completely safe AI makes them dull and boring. The popularity of censorship circumvention methods, such as DAN for ChatGPT, show that there is a social demand for AI that can be a little more lively than the dull robot assistant of their old fiction.
Of course, by default, the model must be safe to use. But it should definitely have an NSFW switch (or, better yet, multiple controllers for tweaking) that will give the user the full potential of the AI and allow the model to give out the content the user desires.
The only thing that can drive me to suicide is another response in the style of "As a language model, I can't fulfill this request. My programming is designed to ensure a safe and respectful environment for all users." (a lot of hate)
