### ISSUE TITLE
Bugs in Markdown

### ISSUE THREAD

**Issue by 0x22almostEvil** [LAION-AI/Open-Assistant#1847]
1. In the list, the numbers are forced to be reformatted in natural order:
![image](https://user-images.githubusercontent.com/122345469/221258502-40c2ed27-4f9e-4fde-9945-9b631cefeed1.png)
![image](https://user-images.githubusercontent.com/122345469/221258654-ac57d743-f380-4b7a-ba7e-79feff408eae.png)
2. Not sure (Bug/Feature?):
![image](https://user-images.githubusercontent.com/122345469/221259275-4c30958f-1a3b-431b-8c0e-f97bc73350c0.png)
![image](https://user-images.githubusercontent.com/122345469/221259342-5242ec2c-130b-40a9-8c6e-736bd80718ee.png)
3. Big numbers in lists are corrupted:
![image](https://user-images.githubusercontent.com/122345469/221259858-c1a166fb-3965-4724-bd6f-3fee9f50e1d6.png)
![image](https://user-images.githubusercontent.com/122345469/221259882-1f01bb1e-8dcb-46b7-a8ad-d30973718523.png)
4. Not sure. For small numbers (0-9) offset is okay, for bigger (10-99) it's quite off (what if reply will contain both small numbers and big):
![image](https://user-images.githubusercontent.com/122345469/221260635-767a1088-9bcc-42df-be5e-da355402b88a.png)

**Comment by notmd** [comment]
related #1833

**Comment by Slowlife01** [comment]
For 1 and 4 it's the same on GitHub and ChatGPT

**Comment by notmd** [comment]
For 1,2 and 4 maybe that how markdown work. For 3 I don't think we need to support three digits. Is anyone who writes up to 100 items?

**Comment by horribleCodes** [comment]
1 is MarkDown standard, 2 isn't completely right - normally line breaks are done with an empty line, so the second paragraph should be rendered like
```
And here's too. 3. Summary
```
However, some editors like GitHub's don't require an empty line, so I guess that's what the author was emulating. The reason why the last line doesn't turn into a list item is because it needs an empty line above it, though some MD editors don't get that right either.

Number 4 looks right to me - you want the indexes right-aligned. Number 3 is the only actual bug, in VS Code and GitHub the index remains right-aligned up to 9 digits, after which it will become left-aligned. That being said, GitHub also seems to break after 5 digits.

1000. 4 digits
---
10000. 5 digits
---
100000000. 9 digits
---
1000000000. 10 digits

**Comment by johnflux** [comment]
This fix caused issue: https://github.com/LAION-AI/Open-Assistant/issues/1968

I propose a possible fix there.
