### ISSUE TITLE
Invalid avatar images

### ISSUE THREAD

**Issue by someone13574** [LAION-AI/Open-Assistant#1985]
Some users who account is linked to a discord account have an avatar image which is pointing to an invalid image. This results in the text "*User's* avatar" which overlaps their username on the leader board. Here's an image:

![image](https://user-images.githubusercontent.com/81528246/222994135-4a7ab23f-7def-422a-9e55-700a889abf06.png)

It can be viewed simply by going to the overall leader board where there are three examples of the broken avatars.

**Comment by owen-duncan-snobel** [comment]
I can take care of this one

**Comment by AbdBarho** [comment]
Ok after a bit of digging, these are the callbacks that are called when a user logs in (using discord), in this order:
```
signIn callback
jwt
signIn event
```

Whenever a user does a full page navigation, the following gets called:
```
jwt
session
jwt
session
```

I assume 2 times because SSR + browser.


It does not seem to be the case that we have a lot of options when we want to do a refresh of the users Image, our session is 30 days, and unless you don't open the website in 30 days, `login` will never be called.

At the same time, updating the user's image on every session would be too aggressive, we are going to have to find to find a middleground.
