### ISSUE TITLE
Suggestion: AGPL would be a more suitable license since this is likely to see use as a web service

### ISSUE THREAD

**Issue by ChristopherKing42** [LAION-AI/Open-Assistant#218]
I suggest considering an AGPL license. The AGPL license grants users freedoms even if they use the software through a web service instead of on their own machine. I could see Open Assistant and it's derivatives being very useful as web services!

(Note that the old code would need to keep notices stating that old versions of it are available under the Apache license.)

**Comment by yk** [comment]
I'm not an expert on AGPL, but wouldn't that seriously limit the potential of businesses to build OA into their (proprietary) applications?

**Comment by ChristopherKing42** [comment]
Yes, but they would still be free to use it in their open source applications. In particular, all downstream applications would still be open source AI.

A particularly successful example recently of AGPL is Mastodon (and most other parts of the fediverse). There are companies that use Mastodon or even make their own forked version, and those forks are also open source.

**Comment by ChristopherKing42** [comment]
Although slightly controversial in the open source community, another option would be to dual license with AGPL. So if, say, Stability provides compute, you could set it up so the public gets access to the AI under the AGPL license, but Stability gains the option of using it under a proprietary license that doesn't require them to follow the AGPL.

AGPL is popular with this sort of scheme because it gives the full benefits of an open source network license, but is compatible with more kinds of business models for the business given the proprietary license.

**Comment by bitplane** [comment]
I see the appeal, but there are down-sides:

* Code made for this project would not be allowed to be used in non-AGPL projects, limiting re-use of the things we build. The AGPL has good intentions but it's terrible license for code re-use; it and the GPL are the reason license checkers exist.
* Individuals who are opposed to the AGPL will not contribute; not everyone is a software socialist. I personally share freely and think everyone should, but I prefer the WTFPL because I don't like to force my values on others.
* It will stop businesses and entrepreneurs from contributing to the project. This will limit real world use and mean it's actually available to fewer people.

**Comment by bitplane** [comment]
> Although slightly controversial in the open source community, another option would be to dual license with AGPL

"You give us full access to use your code, and in return we give you restrictive access to ours" - nobody contributes to those projects unless they're fixing a bug or they bought a commercial license. That's not free software, it's freemium wearing a fake beard and $200 sandals.

**Comment by ChristopherKing42** [comment]
> It will stop businesses and entrepreneurs from contributing to the project. This will limit real world use and mean it's actually available to fewer people.

This is not true of every AGPL project. Mastodon has received a ton of funding recently and is used by probably thousands of businesses and entrepreneurs at this point. It's not even dual licensed; it's straight AGPL.

In my view, though a bigger problem than slightly fewer businesses using it is businesses using it, but closed source. You miss out on a ton of AI that could've been open source but isn't because they made the derivative work proprietary.

**Comment by yk** [comment]
We want OA to be both used and included into apps, open-source and proprietary. All major ecosystems like Tensorflow & Pytorch are permissively licensed exactly because of that. I agree, we might miss out on someone's improvement to the system because they're not forced to share it, but in turn we will massively benefit from unrestricted adoption. As soon as you enter the realm of restrictions via licensing, a huge chunk of potential adopters drops away, many of which would voluntarily contribute to the project (even though they are not forced to).
I personally would not contribute to OA if it was an AGPL project or a dual-licensed project, probably not even to a GPL project. These licenses have their place, but not in a project like this, where the goal is widespread adoption.

I'll leave this issue open for a bit, but I don't see us using anything but the most open, permissive licenses.

**Comment by fozziethebeat** [comment]
I agree with Yannic.  

Each license has it's own place and purpose.  There's plenty of models and data systems with permissive, semi-permissive, and fully closed licenses.  To ensure access to these types of models, someone has to create the models and related infrastructure with the most permissive license possible, otherwise someone would be left out.

As it stands, the current license matches the overall goal and intent of the project.  It's not clear how AGPL would benefit this project given it's limitations.

**Comment by ChristopherKing42** [comment]
I think it's a bit misleading to think of copyleft as "restrictive". AGPL grants companies the freedom to use, study, modify, and even [sell](https://www.gnu.org/philosophy/selling.en.html)  the software or any of its derivatives, and furthermore grants the same rights to downstream users. It's just due to the way that legalese works that the license must phrase this as a restriction; copyright is a restriction on downstream users, and thus granting additional rights to those users must be phrased as restricting copyright.

But I understand that for certain business models it might be too strong. Since the chat bot will be kind of like a library for many applications, another recommendation supported by the free software foundation would be LGPL, which is much weaker (see https://www.gnu.org/licenses/license-recommendations.html#libraries). But I'm not too picky personally; I'll probably try to contribute regardless of which open source license is used. I just thought it was worth consideration.

**Comment by bitplane** [comment]
It's a socio-political stance, to restrict what developers can do for the benefit of end-users. I was an FSF member for a decade so I understand their stance against Tivoization and software patent abuse. If copyleft had become the dominant mode of free software development and software patents weren't a thing then the AGPL would be a very reasonable choice, but the world didn't go that way, and unfortunately for Stallman (who I have a lot of respect for) and the FSF a second copyleft revolution is unlikely. The key problems are:

1. Any company developing products that use AGPL software have to give their code to everybody who uses their software, including their competitors. This means startups and established companies avoid AGPL and GPLv3 software like the plague that it is (GPLv2/LGPLv2 use is usually fine, depending on application)
2. Any company that contributes code to an AGPL project gives an implicit patent grant to anyone else who uses their code. This means that legal teams in most corporations strictly prohibit their employees from contributing to these codebases. It removes their IP monopoly, weakens their patent warchests and may have complex implications for legal agreements that they're already in, including non-obvious ones that can only be tested in the courts. 
3. The license is viral and incompatible with freer licenses, so the two above points apply to any project that incorporates any of the code written for an AGPL project.

I spent a ton of time removing AGPL code from a commercial product last year because it was an existential threat to the business that almost accidentally included it. It's a dangerous license, I'd be surprised if people haven't been sacked for using it.

**Comment by olliestanley** [comment]
I think this can be closed at this point
