### ISSUE TITLE
Add a message to encourage users to give feedback with thumbs up/down for generated messages.

### ISSUE THREAD

**Issue by Quarks-1** [LAION-AI/Open-Assistant#2845]
Making a new issue based on a request in issue #2794 . Message purpose to encourage users to use the upvote and downvote feature more

**Comment by amitag2** [comment]
I'd like to work on this!

**Comment by olliestanley** [comment]
> I'd like to work on this!

Thanks. I have assigned you

**Comment by amitag2** [comment]
@andreaskoepf @olliestanley is this type of feedback message ok?
![image](https://user-images.githubusercontent.com/98849921/234151266-2e619783-a213-4dbf-8cfa-4790befae53b.png)

**Comment by davidak** [comment]
@amitag2 i think it's not only asking about helpfulness. That would be a next step to be able to label it in more details.

Maybe something like: "Please give us feedback if the response is good, so we can improve them."

More a Call to Action (CTA) instead of a question.

**Comment by andreaskoepf** [comment]
@amitag2 Are you still working on this issue or should we try to find someone else to propose a text/design?

**Comment by andreaskoepf** [comment]
> where do you want to store the responses to the message?

I am not not sure what you mean by "responses". The actual thumbs up/down voting functionality it already full implemented and available in the chat interface. The user feedback is stored in the database in the "score" column along with the message. This issue is only about adding a motivational message for the user to provide feedback about the quality of the generated message.
