### ISSUE TITLE
Models not found

### ISSUE THREAD

**Issue by 136William136** [LAION-AI/Open-Assistant#2897]
Hello. I tried to deploy the project with docker on my own server. I tried all models listed in model_configs.py and almost all of them  'is not a folder' or 'cannot be found on hugging face' so that my worker process alway shutdown quickly. I can only run the default distilgpt2 model which gives some nonsense answer. Anyone know any other working models?

**Comment by 136William136** [comment]
![image](https://user-images.githubusercontent.com/128681247/234269151-424d019d-e1e3-41a7-9fec-50bf68607781.png)
also some model work such as OA_SFT_Pythia_12B cannot connect to server.

**Comment by AbdBarho** [comment]
Can this be closed now?

**Comment by smeyerhot** [comment]
How would one go about loading the llama models given we have the weights? Is there some docs on this?

**Comment by olliestanley** [comment]
> How would one go about loading the llama models given we have the weights? Is there some docs on this?

Probably upload them as a private model to your HF account, add a model config pointing to them, and configure your HF credentials for the server so it can access the private model

**Comment by smeyerhot** [comment]
@olliestanley do you mean there is no way to load models from your local machine and all models are pulled in from huggingface?

**Comment by olliestanley** [comment]
@smeyerhot Sorry, only just seeing this. You could put the models in your worker's Docker container. But if you upload them to HF it becomes more easily reproducible because whenever you spin up a new worker it can get it from the same place. Several directions are being explored for the project including PEFT, this is at the moment just exploratory/experimental work
