### ISSUE TITLE
Running OA_SFT_Pythia_12B local inference with GPU support

### ISSUE THREAD

**Issue by velascoluis** [LAION-AI/Open-Assistant#2957]
Hi, I'm trying to run on a cloud VM the inference setup using the steps on the `inference`  folder. 
Been able to run ok the `distilgpt2`, now I want to try the `the OA_SFT_Pythia_12B model`

Any guidance on how to modify the `docker-compose.yaml` , inference-worker,  to use the GPU on my machine.

**Comment by phalexo** [comment]
There is a guide here https://forum.level1techs.com/t/open-assistant-12-billion-parameters-ought-to-be-enough-for-anyone-quick-setup-guide/196202

I have run into a problem that I am using CUDA 11.3 and the docker containers OA sets up insist on using CUDA 1.8 and higher. I have not figured out how to clean it up.

You may not have this problem since you can do a fresh install of CUDA 11.8 or 2.0 and may get it to work.

I'd be interested to know if you are successful in getting it to run.

They need some guide on how to tweak software versions, as people have different setups.
