### ISSUE TITLE
Integrate AutoGPT

### ISSUE THREAD

**Issue by mediafill** [LAION-AI/Open-Assistant#3045]
Would love if you integrate chatgpt for multiple stage tasks and chrome access, or build a similar engine.

**Comment by olliestanley** [comment]
This will need more detail to become a real task

**Comment by kyr0** [comment]
+1 :) -- I guess AutoGPT could simply be forked and a compatibility layer for OA could be implemented, making the ApiManager here more abstract with providers: - OpenAI, OpenAssistant and the model providers here having a type attribute that maps which AI provider they belong to:
- https://github.com/Significant-Gravitas/Auto-GPT/tree/master/autogpt/llm/providers
- https://github.com/Significant-Gravitas/Auto-GPT/blob/master/autogpt/llm/api_manager.py

For the AI Provider, the API endpoint needs to be configurable, so that it could either point to a local endpoint or a Huggingface one. As all the surrounding code should be more or less independent of the AI that runs behind the scenes, the api_manager should hopefully be the primary target for impl.

**Comment by laurentperez** [comment]
I'd downvote this (👎 ?). The whole point of OA vision https://github.com/LAION-AI/Open-Assistant#slide-decks is to offer Apache licenced code and training data CC BY 4.0.

AutoGPT builds upon the _for-profit_ OpenAI GPT-4 API where Microsoft has exclusive access to the code, and has no publics plans to reveal their model weights nor open source them. 

@kyr0 's comment is good. OA could be a provider, thru an impl of thru AutoGPT [plugins](https://github.com/Significant-Gravitas/Auto-GPT-Plugins). But is the _vision_ compatible ? ;)

**Comment by kyr0** [comment]
@laurentperez Thank you for your feedback! I def. agree that OpenAI is nowhere near the direction the community would like to go. The whole point is that the model is open source! :) However AutoGPT implemented OpenAI but AutoGPT itself is open source and their community seems to have an open source vision as far as I can see. I cannot speak for them but I'd wonder if they wouldn't dislike the closed source nature of OpenAI. 
![Bildschirmfoto 2023-05-07 um 13 13 37](https://user-images.githubusercontent.com/454817/236674148-8225094e-68ad-4d45-a2d1-b8900b0dba76.png)

I was coming from a point of efficiency. When AutoGPT already builds a great ecosystem for the Auto/AGI ideas, with plugins etc. to fulfill these goals: Why not consolidate the community effort? MIT and Apache licenses would be  compatible. On the other hand - thinking philosophical/critical in all directions: Why not empower the momentum here and implement ReAct/MRKL features and an ecosystem for that here? But I don't know how much these features fit the vision of this project as I haven't seen that point in the slide decks?

**Comment by mediafill** [comment]
AutoGPT accepts other models or could be edited to use Laama? As I see it, if you don't offer what AutoGPT is (task - > multi-task, execution , the project will become irrelevant rather quickly.

**Comment by kyr0** [comment]
A few days more into researching the topic I conclude for myself: Just use https://langchain.readthedocs.io/ and let the OA focus on what it is best at: Making a LLM model of great quality
