### ISSUE TITLE
Could someone suggest which model is AVAILABLE now, can fit in 300GiB on the host, and be at least somewhat....

### ISSUE THREAD

**Issue by phalexo** [LAION-AI/Open-Assistant#3135]
responsive?

Also, what needs to be modified to run it.

Thanks.

**Comment by olliestanley** [comment]
OA Pythia 12B models are directly available and all the LLaMA 30B models on the site can be acquired using the XOR weights

https://huggingface.co/OpenAssistant

All fit in 300GiB but all will be slow unless you use a GPU for inference

**Comment by phalexo** [comment]
Is it possible to split the models over multiple GPUs using the python
accelerate module? I have 4 GPUs but they have only 12.3GiB each.

**Comment by olliestanley** [comment]
> Is it possible to split the models over multiple GPUs using the python accelerate module? I have 4 GPUs but they have only 12.3GiB each.

It is possible to run models across multiple GPUs. But if you want to use functionality which isn't included in OA inference setup we would recommend just downloading the models separately and using them with other software rather than trying to change the OA inference setup to fit your needs. Most of the features in OA inference would not be needed for most users
