### ISSUE TITLE
Try our assistant button 

### ISSUE THREAD

**Issue by sryu1** [LAION-AI/Open-Assistant#3142]
https://github.com/LAION-AI/Open-Assistant/assets/95025816/9c1ec7eb-4eb5-47c2-96a3-1101df12e6d7

Another one too hard to explain with words...

**Comment by sryu1** [comment]
You can click anywhere on the same "axis" should I say? And it'll go into chat.

**Comment by sryu1** [comment]
It's not my first issue nor contribution by the way 😆

**Comment by olliestanley** [comment]
> It's not my first issue nor contribution by the way 😆

Good first issue means that it would be a good task for a new contributor to try to fix (e.g. because it relatively small/simple to fix)

**Comment by karlji** [comment]
Hi, I am just a beginner, but I checked it out and it seems to me that problem is that by default Flex container has property `align-items: stretch`, which causes the link to spread across the whole "line" as you called it.

It can be fixed by adding `align-self: flex-start;` to affected `a` flex item.
E.g. `.css-1811skr a {
  align-self: flex-start;
}`

I hope it helps to point someone to fix it. I am not experienced enough to fix it myself :)

**Comment by sryu1** [comment]
> > It's not my first issue nor contribution by the way 😆
> 
> Good first issue means that it would be a good task for a new contributor to try to fix (e.g. because it's relatively small/simple to fix)

OOOOH, ok.

**Comment by karlji** [comment]
I think I found a solution at the end. I will send pull-request in few mins.

**Comment by sryu1** [comment]
It seems like the glitch still persists...

**Comment by sryu1** [comment]
Seems like it's fixed now.
