### ISSUE TITLE
Implement Celery task for Discord notifications of reports

### ISSUE THREAD

**Issue by olliestanley** [LAION-AI/Open-Assistant#3517]
The previous implementation caused a bug and so is reverted by #3516

**Comment by nablabits** [comment]
Hi @olliestanley , I'm happy to give this a try. I've managed to get the dev server running locally and spotted where that button lives and what are the methods called. I have a couple of questions:
- Did you revert the previous implementation as a quick fix or rather because it was a dead end? I say so because if it was a quick fix I can reinstate it and debug it.
- If it was a dead end, do you have in the code base some similar task I can take a look at as a guide?
- Finally, do you have a discord channel sandbox that I can use to test the messages arriving? Alternatively I can set up something on my own

Chances are this issue might have a steep learning curve, so if anyone more knowledgeable is keen to pick this up, feel free, I'm happy with the learning experience anyways.

**Comment by olliestanley** [comment]
> Hi @olliestanley , I'm happy to give this a try. I've managed to get the dev server running locally and spotted where that button lives and what are the methods called. I have a couple of questions:
> 
> * Did you revert the previous implementation as a quick fix or rather because it was a dead end? I say so because if it was a quick fix I can reinstate it and debug it.
> * If it was a dead end, do you have in the code base some similar task I can take a look at as a guide?
> * Finally, do you have a discord channel sandbox that I can use to test the messages arriving? Alternatively I can set up something on my own
> 
> Chances are this issue might have a steep learning curve, so if anyone more knowledgeable is keen to pick this up, feel free, I'm happy with the learning experience anyways.

I think the previous approach was fine in principle, but there was a bug causing the report function to be broken entirely, and we wanted to fix prod ASAP so just reverted the change.

We don't have a sandbox, you might have to set something up for that unfortunately.

Hopefully this should be a fairly small change so would be great if you could take a look!

**Comment by nablabits** [comment]
Cool, thanks for the answers, I will work through this these days and will let you know if I get stuck :crossed_fingers:
