### ISSUE TITLE
chats disappeared

### ISSUE THREAD

**Issue by jimhabegger** [LAION-AI/Open-Assistant#3695]
I have one account with my email address, and another one with my Google account. Yesterday all of my chats on both accounts disappeared, and now I can't start any new chats or post any messages. I closed this issue because I forgot to search before I started it. Then after not finding any current reports about it, I opened it again.

**Comment by gomez-L** [comment]
I observed the same.

**Comment by WilliamTokunaga** [comment]
im observing the same problem. i wonder what is the reason behind

**Comment by davidak** [comment]
I can still load https://open-assistant.io/chat and get the static content, but it seem not to be able to load data. Request to URL https://open-assistant.io/api/chat?include_hidden=false fails (404). Maybe the backend is offline?

![Screenshot from 2023-09-25 03-26-58](https://github.com/LAION-AI/Open-Assistant/assets/91113/ba75fba2-6544-4067-810d-302d7e4e67e2)

**Comment by metal3d** [comment]
3 days without any answer from admins.

We know that you don't owe us anything, that the project is being offered free of charge, and so on. But we also spend time labelling content, correcting answers, and we'd like to continue using the chat while offering you our collaboration.
Without a response from you, we feel you're abandoning us, or even taking advantage of our contributions to "suddenly" shut down the service.

We're clearly hoping that this isn't the case, that we're just kidding ourselves and that there's just a communication problem. And that the interface bug has just not been brought to your attention in time. However, on Discord and here, many are concerned...

**Comment by arcticfox2242** [comment]
You don't suppose they let us use open assistant for free intially and then disappearing with community work?

**Comment by theridon** [comment]
> You don't suppose they let us use open assistant for free intially and then disappearing with community work? Cause if they do, major dick move.

I don't think we should jump to conclusions, maybe it just needs a fix. Have they said anything about this?

**Comment by metal3d** [comment]
> You don't suppose they let us use open assistant for free intially and then disappearing with community work? Cause if they do, major dick move.

The fact that no one is responding after several days, either on Discord or in the GitHub issues, may lead many of us to think this kind of thing. It wouldn't be the first time a project decided to do something stupid like this.

My guess is just an expression of a fear that was shared on Discord (not by me), and I think it highlights that lack of communication during a service outage can lead to this kind of talk.

So please don't shoot the messenger, understand him, and respond diplomatically.

**Comment by stefangrotz** [comment]
Andreas talked in several podcasts about the fact that the heavy unpaid workload isn't sustainable and can't go on for ever. Maybe the team just has different things to do right now in their private life. Give them at least a few weeks to react, this is still an open source project.

**Comment by metal3d** [comment]
> Maybe the team just has different things to do right now in their private life

A simple message on the web page "we have some points to fix" takes a few minutes. Answer here, labeling "in progress" is a simple click. There is a team, there are several managers.

The website is used by thousands of users / contributors. 

Of course, it's free. But the communication is important in this case.

**Comment by metal3d** [comment]
I just want to give a precision. I just explained on Mastodon that there are many open source projects to use AI with respect of privacy. Then, I gave open assistant as a "good example". The answers were "LOL, great, there is no chat"...

I cannot defend the project now... Because I don't have explanation to give to the bad comments, and I cannot defend that it works...

The problem is that the "open source" image is impacted when no one gives a status on outage.

**Comment by stefangrotz** [comment]
I understand your frustration and this actually happens very often with open source project. I think they should be clearer about the fact that the website is more a proof of concept and a tool to collect the dataset. But it is not meant to be a website that is used by millions of people. 

I actually would prefer a paid model by a third company who hosts the OA model.

**Comment by jimhabegger** [comment]
I can't imagine how there could be any good reason for no word at all in four days, but maybe there is. Doesn't anyone have any way to contact any of the developers or admins?

**Comment by fireYtail** [comment]
Guess political agendas did their thing and now Open Assistant is forbidden/banned. When will they stop this nonsense censorship? They want to spread the message that AI is dangerous and "stop" it because they want it only for themselves to control - to use it to their advantage for their political purposes, including censorship, misinformation and brainwashing.

**Comment by fireYtail** [comment]
> I actually would prefer a paid model by a third company who hosts the OA model.

So that they can make it "Closed Assistant" and do the same kind of thing OpenAI has done with Dall-e 2, forbidding certain subjects that they deem censorable (like Ukraine) or silently modifying prompts to forcefully add "diversity" to the output images you're paying for (such as gender, nationality, skin tone, sexual orientation, etc) ?

To be honest, I would much rather not let Open Assistant become a tool to enforce political agenda and give this agenda (in incognito/undercover ways) a false sense of "legitimacy" that it doesn't really have in our society.

**Comment by stefangrotz** [comment]
Calm down, the models are freely downloadable. Everyone can run them. Right now Open Assistant is completely depended on donated GPUs from big companies. A payed service (or more than one from different countries) would be more free. Right now they are depended on donations by companies.

**Comment by jimhabegger** [comment]
They aren't responding on Discord either, but maybe we could find some contact information on the laion.ai website, for people who may or may not answer questions about what's happening.

**Comment by fireYtail** [comment]
> Calm down, the models are freely downloadable. Everyone can run them or even change them. Right now Open Assistant is completely depended on donated GPU time from big companies. A payed service (or more than one from different countries) would grantee independence.

That's right, because everyone has a computer with 24 GB+ of VRAM in their home.

And no, splitting it between 2 or 3 companies would not guarantee independence. Censorship has no mercy and enough money (or other means such as violence, be it legal or illegal) will ALWAYS silence any company or person's voice.

The fact that they haven't said a word speaks for itself, I hope to be wrong but they probably had the safety of close relatives threatened, hence the permanent silence and "no signs of life".

**Comment by stefangrotz** [comment]
They literately released a new German model today: https://laion.ai/blog/leo-lm/
Please go out and get some fresh air.

**Comment by fireYtail** [comment]
> They literately released a new German model today: https://laion.ai/blog/leo-lm/ Please go out and get some fresh air.

And who is running it? Where's it available to use?
I don't tell you what to do. You don't give me orders either.

**Comment by stefangrotz** [comment]
It is in the first paragraph of the article
![image](https://github.com/LAION-AI/Open-Assistant/assets/5982239/c13de45d-052c-4eda-9db3-ecd6cf1529a5)

I am out of this discussion here.

**Comment by fireYtail** [comment]
> I am out of this discussion here.

Come back whenever Open Assistant is available... Everyone's waiting...... And then, you tell me how wrong I was ;)

**Comment by jimhabegger** [comment]
Announcement on Discord:
"Yannic Kilcher (gh: yk) — Today at 5:02 AM
Hi everyone, we've disabled chat on the website for now (it was financed privately). We'll give you some more updates soon.
The models remain available to download / self-host / etc."

**Comment by fireYtail** [comment]
> Announcement on Discord:
> "Yannic Kilcher (gh: yk) — Today at 5:02 AM
> Hi everyone, we've disabled chat on the website for now (it was financed privately). We'll give you some more updates soon.
> The models remain available to download / self-host / etc."

Thanks for the greatly detailed "explanation" as to what has happened. It really cleared things up.

Let's do as he suggested and let's all self-host the models on our 24+ GB GPUs computers that we all have at home.

Also nice to see how only the chat is disabled, because it's okay if the chat's not available, but it's not acceptable if people stop contributing in exchange for nothing (while the chat is disabled with no word on it ever coming back)

> You don't suppose they let us use open assistant for free intially and then disappearing with community work?
> Cause if they do, major dick move.

I second this.

**Comment by sryu1** [comment]
Hey, let's think realisitically. We are all open source developers, no one affiliated get's paid any money to do anything. We all currently clearly depend on sponsorships of third party companies. You may say let's host the models in our 24+ GB GPUs, but we don't have them because they're expensive, right? Ever thought about how expensive it may be for those companies to host our Open Assistant models with a heap of people using it simultaneously? Maybe they got sick of investing their compute on us... Now I'm just saying my opinion and thoughts on this, and I'm sure that the leadership team for OA is working hard in the background to resolve the issue. We'll just have to wait and see what their updates will be about. 😉

**Comment by fireYtail** [comment]
> We all currently clearly depend on sponsorships of third party companies. You may say let's host the models in our 24+ GB GPUs, but we don't have them because they're expensive, right? Ever thought about how expensive it may be for those companies to host our Open Assistant models with a heap of people using it simultaneously? Maybe they got sick of investing their compute on us...

This is exactly what I'm talking about. No one is doing this for charity or because they want everyone to have access to the AI. Instead, some big third party companies are taking control of everything by sponsoring the project, and the continuity of that sponsoring (and thus the project) depends on whether those third party companies' interests are met or not. Which means you are all subject to what those third party companies want, or you all have no money or computing resources required and cannot continue. In other words, you have to obey to your masters as if you were dogs, and if censorship or any other misuse is the way to go, so be it, because you depend on keeping them happy to have funding.

**Comment by fireYtail** [comment]
> I am out of this discussion here.

I see...

> I work for this project because I want to create an open dataset to train language models and because I want to have models that I can use on my own GPU cloud provider and hopefully in the future (when technology progresses) on a local machine. And that is exactly what I am getting. As long as they publish their models and their datasets under an open licence I am happy. The Chat on the website is a nice extra, but it was always clear that it won't stay for ever.

Will you also be happy when legislation is made so you your GPU cloud provider has to prevent you from using it to run AI?

> What exactly do you expect from this project? I have the feeling that you expect them to start some kind of revolution or something.

Not at all.

I wish for AI to be free for everyone to use and run, not for big companies and governments to take it for themselves and use it on their own benefit and against the rest of society. Making it illegal for others to have access or run it since it would take away this unfair advantage from them for political and commercial purposes.

But you live in the fantasy that they will let everyone with a computer use AI, and lose this unfair advantage against us. I don't expect your fantasy to be our real future.

**Comment by jmaczan** [comment]
Fwiw anyone can now deploy their own LLM for free with Cloudflare's WebGPUs - https://blog.cloudflare.com/webgpu-in-workers/

**Comment by jimhabegger** [comment]
This issue is resolved for me, but I'm not sure if I should be the one to close it, or not.

**Comment by fireYtail** [comment]
> Fwiw anyone can now deploy their own LLM for free with Cloudflare's WebGPUs - https://blog.cloudflare.com/webgpu-in-workers/

The fact you can do it now doesn't mean you'll be able to do it in the future. Cloudflare isn't exempt from having to comply with legislation and regulations. Yes, those don't forbid AI now, but just give them time.

> This issue is resolved for me, but I'm not sure if I should be the one to close it, or not.

I wouldn't say that it's resolved when:
1) The Open Assistant chat is still unavailable (but training it is still possible, because let's get all the data before leaving)
2) We still have no explanation whatsoever as to what has happened nor what to expect. They haven't even said if it'll be available ever again... Although you don't have to be very smart to add two plus two.

**Comment by jimhabegger** [comment]
I still don't know if I should be the one to close this, or not.

**Comment by fireYtail** [comment]
> I still don't know if I should be the one to close this, or not. It looks like a dead issue to me. If we haven't got an answer by now, we never will.

Censorship won once again. RIP Open Assistant.

**Comment by jimhabegger** [comment]
I'm wondering what "open" means, if it doesn't include transparency.

**Comment by fireYtail** [comment]
> I'm wondering what "open" means, if it doesn't include transparency and open, honest communication.

The "open" in open assistant is the same as the "open" in OpenAI. The very exact same.

**Comment by krwb** [comment]
> > I'm wondering what "open" means, if it doesn't include transparency and open, honest communication.
> 
> The "open" in Open Assistant is the same as the "open" in OpenAI. The very exact same. This is what I have been telling you all during these past days. And it wasn't wrong.

The thing is they have told us the problem in the discord, granted it took them a while but in context it makes sense.
Running an ai locally for one person is no easy task and they were running it for thousands if not millions at once, GPUs don't grow on trees so they had to rent services to be able to host the model, this was funded by a private investor who pulled out. Open Assistant didn't stop hosting the chat because they wanted to they stopped because they couldn't afford it.
Ps. Bonus points for the dig at OpenAI I'm just as pissed as you on that one.

**Comment by Kindi-Equinox** [comment]
Someone paid or coerce the previous investor to pull out funding the project, so that some other investor with their own woke or controlling agenda and censorship will come and take over. open assistant RIP.

**Comment by fireYtail** [comment]
> The thing is they have told us the problem in the discord, granted it took them a while but in context it makes sense. Running an ai locally for one person is no easy task and they were running it for thousands if not millions at once, GPUs don't grow on trees so they had to rent services to be able to host the model, this was funded by a private investor who pulled out. Open Assistant didn't stop hosting the chat because they wanted to they stopped because they couldn't afford it. Ps. Bonus points for the dig at OpenAI I'm just as pissed as you on that one.

I've already explained this, is it was as easy as a funding problem, the training from community work would also have become unavailable, which wasn't the case. It's hypocritical from you to try to mask/disguise the obvious while attacking OpenAI.

> Someone paid or coerce the previous investor to pull out funding the project, so that some other investor with their own woke or controlling agenda and censorship will come and take over. open assistant RIP.

Thanks, you were able to sum it up much better than me, indeed I'm bad at summarizing so my explanations were much longer, but saying the exact same because that's how it is and it's idiotic to deny it.

**Comment by sryu1** [comment]
So can you tell us specifically what you are after at the moment?

**Comment by stefangrotz** [comment]
Again: Open Assistant never was about offering a public chat. It was about creating a public dataset and training models that are freely downloadable. Some people from the team financed the chat privately in the last month, and they have every right to stop doing this.

I would be angry if they never published oasst2 though.

Your arguments would have made sense in January, but in the meantime we have tons of open models from all over the world. There is no way anyone can turn back time and somehow make this teconology disappear again. If you are looking for models that you can run locally I recommend having a look at projects like [GPT4ALL](https://gpt4all.io/index.html) or [Stable LM 3B](https://stability.ai/blog/stable-lm-3b-sustainable-high-performance-language-models-smart-devices). The LLM Peer to Peer project [Petals](https://github.com/bigscience-workshop/petals) is another example how it has become impossible to regulate this technology.

**Comment by TechnotechGit** [comment]
> the training from community work would also have become unavailable, which wasn't the case.

The fact that models are still being trained is something to be grateful for. If you take a look at Hugging Face, you’ll notice plenty of 3-7B models that can even be run on a phone. If you can’t run those, it’s not the creator’s problem. 

The lack of communication from OA “leadership” on this thread is a bit disappointing. However, the main topic of this issue, hosting the models, most likely is an issue of cost. It’s not cheap to host models 24/7, and Open Assistant was never even about the model, but the dataset. The collection of data is for public release, as evidenced with oasst-1 (yes, I’m aware we’re still waiting on oasst-2).

Initially, we had Pythia, then Llama 1, then MPT and Falcon, then a flurry of other models, and then Llama 2. Now we also have Mistral (7B only). The initial training of OA was on Pythia, and it was a decently capable model at the time. Things have changed, and those models are now outdated. However, the dataset can still be used to train newer and more capable models because of advancements in base models. The Open Assistant models and the dataset will never disappear, they're on Hugging Face, and they've been downloaded by thousands.

**Comment by fireYtail** [comment]
> So can you tell us specifically what you are after at the moment?

I could make the same question, since it's crystal clear to everyone on this thread that it isn't coming back.

> some companies supported this project, and they have every right to stop doing this.

Stop, as in how Elon Musk, an important part of the reason of OpenAI's existance, alarmed everyone to "stop" AI, to gain some time for themselves? I don't think those "stops" are a "right" that companies have. Specially when those companies are subject to agendas.

> The fact that models are still being trained is something to be grateful for.

It is something to be grateful for, only to the people that are able to run it. If there's gobernments and political dirt in there, I'm not personally grateful that THEY get that training for free.

> models that can even be run on a phone. If you can’t run those, it’s not the creator’s problem.

I thought conversational chatbots from the early 2010's weren't part of this discussion. I took that for granted.

And that's like saying, if you can't live in a bunker, it's your fault if a war arises and your house is destroyed, because bunkers exist. If you don't have access to one, you deserve to not have a roof to live under, and be in mortal danger. Right...... Because I chose most people in our society don't live in bunkers, and I chose to not live in one. Or some idiocy like that. Maybe it would be more realistic to say that the problem lies on the cause of the war, not on the population that die. Or to escape nuclear weaponry you could fly away from the planet, so it's people's blame too that nuclear weaponry exists and can be used against them. Whatever...... I don't have time for this kindergarten.

**Comment by krwb** [comment]
> Censorship won once again. RIP Open Assistant.

I really don't understand where you are getting this from, regardless of what you believe when it comes open assistant's lack of communication it is known that the chat was taken down due to funding issues,

**Comment by JuliaBonita** [comment]
The title of this thread no longer reflects the fundamental direction of the conversation here. So I've posted my comment here:

[The Biggest Problem with Open Assistant Right Now](https://github.com/LAION-AI/Open-Assistant/issues/3713)

I hope the OA team understands that their actions are hurting the entire independent LLM ecosystem. My comment in the other thread explains why.

**Comment by andreaskoepf** [comment]
https://youtu.be/gqtmUHhaplo?si=dwe6p0BxObXSNZyS
