### ISSUE TITLE
Reply as User and Rank User Replies producing undefined properties error

### ISSUE THREAD

**Issue by KarthikRaju391** [LAION-AI/Open-Assistant#407]
The `Reply as User` and `Rank User Replies` produce undefined property errors.

## Reply as User
![image](https://user-images.githubusercontent.com/67912316/210765103-912ccdf7-50f7-4edd-b58b-8e3120958bd2.png)

## Rank User Replies
![image](https://user-images.githubusercontent.com/67912316/210764881-1c499003-b605-4451-a738-eac0c9dccdaa.png)

### This error occurs when trying to view the `messages` section in `Dashboard`

![image](https://user-images.githubusercontent.com/67912316/210765560-93aa6f87-1b4e-44e8-a675-0b8f348c0e47.png)

**Comment by fozziethebeat** [comment]
I think this is due to your docker instance.  There's been cases where running the backend has produced problems which surface in this error.

Can you do the following:
1.  stop all docker containers.  Every that might be running container. 
2. Run `docker compose up frontend-dev --build` at the project root directory.
3. Run `npx prisma db push` at the `website/` directory.
4. Run `npm run dev` at the `website/` directory.

Then make sure you login as a new user (log out if needed) and then try navigating to the tasks.

If that doesn't work, please copy-paste the docker logs for the backend service.

**Comment by KarthikRaju391** [comment]
I had forgot to add the `--build` tag, it is working now. Thanks!
