### ISSUE TITLE
enforce docstrings via pre-commit 

### ISSUE THREAD

**Issue by clstaudt** [LAION-AI/Open-Assistant#420]
Browsing some code from the repo and finding most of it without docstrings makes me think that this is a good idea:

http://www.pydocstyle.org/en/stable/usage.html#usage-with-the-pre-commit-git-hooks-framework

**Comment by yashgosa** [comment]
@clstaudt is this issue still open cuz i wanna work on it

**Comment by bitplane** [comment]
@yashgosa I've assigned you. If you need any help with the process then just ask here or on discord :)

**Comment by yashgosa** [comment]
Sure!

**Comment by yashgosa** [comment]
@bitplane My understanding of what I need to do is not clear, for example, do I need to add docstrings to all functions (which is quite difficult because I do not know how every function works) or should I include pydocstyle as a hook for pre-commit?

**Comment by bitplane** [comment]
Well if you add the pre-commit rule then you'll have to add the docstrings too, as commits will fail afterwards.

Maybe identity a small area that you feel comfortable with to start, use copilot to generate the docstrings then edit them (so they're something more useful than rewording the function name), open a pull request and get feedback on them, then we can add the rule once they're all done?

**Comment by yashgosa** [comment]
@bitplane I have to add `pre commit` to `requirements.txt` but there are many `requirements.txt` and `requirements-dev.txt`. Should I create a new `requirements.txt` in `LAION-AI/Open-Assistant` ?

**Comment by bitplane** [comment]
Hmm that's a good point. I guess most people are using the devcontainer which has pre-commit already installed. It should probably go into the dev dependencies in the `oasst_shared/pyproject.toml`, and we should move to using toml files and installing in dev mode rather than having different requirements.txt files all over the place and relying on implicit package loading by being in the right directory (see the post-install script in .devcontainers/backend for the proper package install process)

If you open vscode in the project dir, does it open the devcontainer and let you use the pre-commit rule? It's probably best to work in there rather than in the venv on your own machine
