### ISSUE TITLE
Internet 

### ISSUE THREAD

**Issue by brecele** [LAION-AI/Open-Assistant#472]
Saya mengalami masalah sekarang jaringan internet data tidak bisa di fungsikan

**Comment by andrewm4894** [comment]
I translated and looks like you having some sort of internet problem. Not sure this is best place to help or not sure what this issue is. 

I'm going to close it for now but we can happily reopen if you can respond with something a bit clearer. Ideally in English if possible or if not maybe include a translation too.

**Comment by brecele** [comment]
I'm having problems with the internet network while the cellular network works

**Comment by brecele** [comment]
![截屏_20230219_232453](https://user-images.githubusercontent.com/121701102/219960999-ac68a69e-2c1e-4641-abd2-f0cfa9bed88f.jpg)
![截屏_20230219_232401](https://user-images.githubusercontent.com/121701102/219961019-c40fdc00-cbff-46e5-a467-307165992a03.jpg)
![截屏_20230219_232321](https://user-images.githubusercontent.com/121701102/219961041-7255917f-fc21-4bb3-9fba-6193300cda63.jpg)
Like the screenshot, my problem is that on my SIM card I use Telkomsel data access and can't appear
