### ISSUE TITLE
Breaks on Mac M1

### ISSUE THREAD

**Issue by sfabriece** [LAION-AI/Open-Assistant#568]
I'm getting the following error when spinning up on a Mac with an M1:

Error response from daemon: platform linux/arm64/v8 not supported

![image](https://user-images.githubusercontent.com/3108592/211304443-0c6c1b00-d872-4182-94cc-f599e498e044.png)

**Comment by fozziethebeat** [comment]
What version of docker do you have?

I have a Mac M1 and I am not seeing any problems right now (tho i have in the past).

**Comment by sfabriece** [comment]
![image](https://user-images.githubusercontent.com/3108592/211311375-f78c025e-fd38-4d80-b0ff-ad5d4c77c8d9.png)

**Comment by sfabriece** [comment]
Any Ideas @fozziethebeat :)

**Comment by fozziethebeat** [comment]
Not yet.  I'm assuming you tried to bring everything up by running `docker compose up --build` correct?

**Comment by sfabriece** [comment]
I did @fozziethebeat. Do you have the same version? 
![image](https://user-images.githubusercontent.com/3108592/211500097-d9080421-d211-49f8-ab50-ae001daa148f.png)

**Comment by fozziethebeat** [comment]
So, I just double checked and it turns out I have a Mac M2, not a M1 (I seem to have forgotten what I recently purchased).  That could be the key problem.

We have the same version of docker.  The one setting difference is that i use `gRPC FUSE` instead of `VirtioFS`.  I'm not sure that would affect this however.

What version of MacOS do you have? I have 13.1 (22C65)

**Comment by sfabriece** [comment]
I have the same MacOS version as you @fozziethebeat. I there any specific reason you are using gRPC FUSE instead of the others?

**Comment by fozziethebeat** [comment]
This was the default setting for my Docker.  I actually haven't inspecting these settings so i'm not quite sure how it got set.

**Comment by yk** [comment]
the `sleep` images can easily be replaced, but it's super strange that the backend image is an amd, because if you're doing `--build`, then that should be built locally. is this due to the base image?

**Comment by Jac-Zac** [comment]
I also have an M1 macbook. By default my docker was also using `gRPC FUSE` which indeed doesn't give error or warnings. On the other hand I tried to reproduce what @sfabriece said and I get the same working though they are still not blocking, those container just run under emulation. In general since `gRPC FUSE` seems to be the default version to be it doesn't seem to alarming since with that it works like a charm.

**Comment by sfabriece** [comment]
@Jac-Zac I didn't understand your previous comment. Did you manage to reproduce my issue? 😄

**Comment by Jac-Zac** [comment]
Yeah sorry. But using `gRPC FUSE` it works for me

**Comment by Jac-Zac** [comment]
And using `VirtioFS` I get the same warnings

**Comment by Jac-Zac** [comment]
Btw, I'm on macOS Ventura 13.1 (22C65)

**Comment by sfabriece** [comment]
Good to know that someone else get the same errors. @Jac-Zac

**Comment by nicosuave** [comment]
There's a regression in Docker Desktop somewhere between 4.15.0 and 4.16.2. The former works fine.

**Comment by olliestanley** [comment]
Looks like this has a solution. Closing it but if anyone still has the problem feel free to reopen

**Comment by nicosuave** [comment]
Disabling experimental containerd support in Docker Desktop solves this problem (broadly, beyond this repo) for me

**Comment by jagui** [comment]
@nicosuave: saved my day 🙇‍♂️
