### ISSUE TITLE
discord-bot shall respond with a help message when it receives unrecognized direct-messages 

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#632]
Currently our discord-bot ignores unrecognized direct-messages from users, e.g. when new users send "Hello" or "help etc. 

- The bot should send a friendly answer with information about the `/help` command
- Currently there is a Slash-`/help` command that can be used in a channel of a discord server on which the bot is running but not in the DM to the bot. `/help` should also be recognized as a help-request when it is received via DM and the bot should respond with its help message.

**Comment by leehanchung** [comment]
I will try to work on this.

**Comment by andreaskoepf** [comment]
@leehanchung are you still working on this? if not I would kindly ask you to unassign yourself.

**Comment by leehanchung** [comment]
On it, will get it out in a couple days. Apologies on the delay.

**Comment by leehanchung** [comment]
@andreaskoepf  Quick question about the expected behavior.

1. On friendly answer. There's a predefined help message already.
2. `/help` command on the bot works in both Discord channel and in DM. Please see below

## In channel
![In channel](https://user-images.githubusercontent.com/4794839/214496675-17e0af9d-d4d1-4f0c-822b-6c40ae499377.png)

## In DM
![In DM](https://user-images.githubusercontent.com/4794839/214496498-b6c8bb2e-c79f-4688-a1d1-0b74b5259ce2.png)

**Comment by andreaskoepf** [comment]
@leehanchung sorry for not replying earlier. Is this issue still open? The bot could reply with a message that informs the user about the `/help` command.

**Comment by leehanchung** [comment]
@andreaskoepf This issue should be closed; the bot already had the intended behavior as shown in the screenshots taken several weeks ago.
