### ISSUE TITLE
Improve instruction for simple spam labeling task

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#707]
The spam yes/no question for the simple-text-labeling with only "spam" label is important.

Please add an instruction text + question to the simple-text labeling task web UI .. e.g. the one which shows No\Yes button (https://github.com/LAION-AI/Open-Assistant/pull/687).

The instruction/description text might be something like this:

"In this step, we want to weed out spam responses, trolling, intentional undermining of our purpose, illegal material, material that violates our code of conduct, and other things that are inappropriate for our dataset. We collect these under the common heading of "spam". Note that this is not yet an assessment of whether this piece of text is the best possible answer. Especially for prompts or user-replies, we very much want to retain all kinds of responses in the dataset, so that the assistant can learn to reply appropriately. Please mark this text as spam only if it is clearly unsuited to be part of our dataset, as outlined above, and try not to make any subjective value-judgements beyond that."

Add a final question that can be answered with the Yes/No buttons.

**Comment by othrayte** [comment]
I'm thinking we should go with something simple like "The message is spam?" and then include one of the more info "(i)" icons with something like the full text mentioned in this issue. At the moment we have descriptions and explanations for the ad hoc message labeling report flag thingy, but we don't send these as part of the labeling task we should consider either including that information in the task or otherwise providing the content from the backend, perhaps by using the existing valid labels api (at a later stage, initially we can just hard code is in the webapp).

I think someone mentioned in the web meeting starting but not finishing this task, if someone isn't already on this and this is acceptable then I'll go ahead and make this change. I'll also fix the surrounding messaging to make more sense for the simple questions case. The following is what I have so far:
![image](https://user-images.githubusercontent.com/241372/212653257-750ca23c-9566-494c-b75e-3e4c242f8d3c.png)

**Comment by andreaskoepf** [comment]
Maybe "Is the last message of this conversation a spam message that should be excluded from the dataset?" 

But you are right that the message to which the question refers (e.g. the last element of the conversation) needs to be highlighted somehow ..

We could also ask the user to voluntarily submit a full report for the last message (by using the report (red '!' in circle) function).

**Comment by othrayte** [comment]
Re: The "... should be excluded ...?" suggestion, I originally had a longer message, but found it didn't fit well in the UI, especially on mobile, I can mock up your suggestion and provide some images if you want. The other thing is I moved away from "_last_ message" as it sounded odd to refer to the only message as the last message when labeling an initial prompt as the same message is currently use for all 3 simple labeling tasks.

Re: highlighting the last message, I'm hoping that #764 will help with that.

**Comment by AbdBarho** [comment]
Text is updated, there are other potential improvements from #842 we will work on.
