### ISSUE TITLE
Leaderboard stats for different time breakdowns are confusing

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#840]
Right now the monthly stats show lower numbers than the daily stats.  We should investigate why and update either how the website fetches the leaderboards or update how the backend returns the stats.

**Comment by andreaskoepf** [comment]
This a side effect of different update intervals. The amount of data to process for the last 24h will be much smaller than for all-time (total) .. you can get the current update intervals (in minutes) via GET `/api/v1/admin/backend_settings/public` : 

```
{
  "PROJECT_NAME": "open-assistant backend",
  // ...
  "USER_STATS_INTERVAL_DAY": 15,
  "USER_STATS_INTERVAL_WEEK": 60,
  "USER_STATS_INTERVAL_MONTH": 120,
  "USER_STATS_INTERVAL_TOTAL": 240
}
``

**Comment by fozziethebeat** [comment]
So with that we could report something that communicates how often the stats are refreshed?  We could say something like "weekly stats refreshed every 60 minutes".  I think people will still grumble about it but at least we explain why things might look odd.

**Comment by andreaskoepf** [comment]
I added a `last_updated` field to the leaderboards/{time_frame} result model:

```JSON
{
  "time_frame": "day",
  "last_updated": "2023-01-19T23:10:15.663238+00:00",
  "leaderboard": [
    {
      "rank": 1,
      "user_id": "2ef9ad21-0dc5-442d-8750-6f7f1790723f",
      ...
```

A very "simple" fix would be to re-calculate all leaderboards simultaneously - then the all-time timeframe would define possible interval. I suggest that we monitor the time it takes to calculate the leaderboard as the database grows. If it turns out that everything is fast enough we can increase the leaderboard-interavals...
