### ISSUE TITLE
Add message counts grouped by lang tag to system stats query

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#904]
Add counts of (non-deleted) messages grouped by their [lang-tag](https://github.com/LAION-AI/Open-Assistant/blob/89f9e5a88700f42351ced059c5cb1b632ccf012b/backend/oasst_backend/models/message.py#L41) to the [system stats query](https://github.com/LAION-AI/Open-Assistant/blob/89f9e5a88700f42351ced059c5cb1b632ccf012b/backend/oasst_backend/prompt_repository.py#L807). The current SystemStats response model can be found [here](https://github.com/LAION-AI/Open-Assistant/blob/89f9e5a88700f42351ced059c5cb1b632ccf012b/oasst-shared/oasst_shared/schemas/protocol.py#L384).

**Comment by dslvt** [comment]
Can I try to do this task?

**Comment by dslvt** [comment]
And is it correct DATABASE_URI?

`DATABASE_URI="postgresql://postgres:postgres@db:5432/postgres"
`

**Comment by dslvt** [comment]
@andreaskoepf

**Comment by hemangjoshi37a** [comment]
Thanks for bringing up this issue! I can understand how this could be frustrating.

Regarding the issue you're experiencing, it sounds like the problem may be related to the configuration of your environment. In order to properly troubleshoot the issue, it would be helpful to have more information about your setup, such as the version of the library you're using and the version of Python you're running. Additionally, it would be helpful to see the full traceback of the error message you're receiving.

One solution to this issue could be to try updating to the latest version of the library. This may resolve any compatibility issues that may be causing the problem. Another option could be to try running the code in a different environment, such as a virtual environment, to isolate any potential issues with your current setup.

Additionally, I would like to suggest that you could try to check the logging and see whether it will throw any error message which could be helpful in debugging.

Lastly, if you're still experiencing issues after trying these solutions, please don't hesitate to reach out for further assistance. We're here to help, and we'll do our best to help you resolve the problem.

Please let me know if these suggestions help or if there's anything else I can do to assist.

Also, I would like to suggest that you could also try to reproduce the issue in a minimal example, and share that, it could help other contributors to quickly reproduce and understand the problem.

**Comment by kingychiu** [comment]
Hi, I am picking this up. I have got the local dev server running. Based on the @andreaskoepf  comment above, I think the API is `http://localhost:8080/api/v1/stats/`

I am trying to call that API from swagger but am encountering an auth error.


![Image](https://user-images.githubusercontent.com/11500136/216778454-1f8f3f4e-9103-472a-8ac6-2f869353b0bc.png)

 
Please advise. How can I authenticate myself via swagger? Or should I be able to do this ticket by only unit test (if any)?

Thank you

**Comment by kingychiu** [comment]
I am able to call the API with X-API-Key=1234,
It is defined under the Setting:

```
class Settings(BaseSettings):
    PROJECT_NAME: str = "open-assistant backend"
    API_V1_STR: str = "/api/v1"
    OFFICIAL_WEB_API_KEY: str = "1234"
```

**Comment by kingychiu** [comment]
PR created
https://github.com/LAION-AI/Open-Assistant/pull/1101
please review.

**Comment by kingychiu** [comment]
Hi, @andreaskoepf any feedback on this PR? It has been here for 2 weeks. Please let me know if it fits the requirements.

**Comment by olliestanley** [comment]
Closing as #1101 is merged
