### ISSUE TITLE
Simpify message feedback UI to Thumbs Up/Down

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#917]
Right now responding to arbitrary messages is fairly complicated, it's for reporting and has a long list of labels.  To simplify it and get cleaner more frequent data we should switch to a simple flow:
1.  A inviting review button
2. A simple thumbs up/down option
3. An ability to provide more detailed labeling only if desired (via a `say more` link).

**Comment by othrayte** [comment]
If someone can assign me to this one I'll start the website side.

**Comment by fozziethebeat** [comment]
When this is done we should make sure the user experience is better than what's described in #927

**Comment by andreaskoepf** [comment]
> If someone can assign me to this one I'll start the website side.

Super cool. I merged the inital emoji PR. I guess we need the information about which emojis were set by the current user. Will try to add this later today.

Not sure where we would want to place the add-emoji functions ... some ideas here (only showing possible positions ... no design proposal ;-)):

![image](https://user-images.githubusercontent.com/9976399/214522037-a965dbe8-e2da-45e3-b5c7-1775a7884576.png)

**Comment by andreaskoepf** [comment]
(probably we should add :clap: to the emoji set too)

**Comment by mashdragon** [comment]
We might want to keep the emoji button away from the report button.

**Comment by othrayte** [comment]
This is what I have so far: (keep in mind that this is a UI mock up and not yet hooked up to the API and I haven't yet aligned this with the API so I still need to add a way to add the rest of the emoji reactions.

The reactions will appear if any user has reacted with that emoji. Note this use has up voted with a thumbs up but not down voted with the thumbs down and noone has reacted with the other emoji. Clicking on a reaction would undo the reaction if the user had that reaction already, otherwise it will add to the current count.
![image](https://user-images.githubusercontent.com/241372/214786050-180c752e-e645-4f14-a469-4a497683840a.png)

The overflow menu is always present and adds a way to react, label, or report.
![image](https://user-images.githubusercontent.com/241372/214786096-64412d2f-9529-4617-aa2e-11e1b65d54e4.png)

Unrelated: I'm also thinking that we would add an option to the menu to open the message in a new tab. At the moment you can only go to the messages in the messages view and not from the tasks. We can add the ability to go to the task in a new task by clicking on it in a task but I don't think that is a good experience on mobile.

**Comment by fozziethebeat** [comment]
I like how clean and simple this UI is.  It can easily be ignored but also looking at it I intuitively know what to do.

**Comment by othrayte** [comment]
I also really like the clean outline icons, but we don't have (or I have not found) icons to match for all the emojis the backend currently allows. I have added the full set now and it looks odd to have a mix. I would really like it if we could have outline icons for all the emoji but I don't know if there is somewhere we can get them (I suppose we could also just do them ourselves).
![image](https://user-images.githubusercontent.com/241372/214811506-1b10b5db-f9ad-4287-9a4f-f8d0287964a2.png)

**Comment by andreaskoepf** [comment]
@othrayte we can simply reduce it to the clean icon set .. and ignore/remove the other emojis. Thumb up/down + flag is the really required feature set!

**Comment by andreaskoepf** [comment]
backend functionality was merged https://github.com/LAION-AI/Open-Assistant/pull/937

**Comment by hemangjoshi37a** [comment]
Great work on simplifying the message feedback UI to Thumbs Up/Down! I agree that this will make it much easier for users to provide feedback, and it will likely lead to more frequent and cleaner data.

Additionally, I would recommend to keep the back-end part also in mind, as it might have an impact on the final implementation, and it could be mentioned on your reply in order to show the context of the whole process of the modification. And if you have any live example of the UI, linking to it would be a good idea to show the progress in the issue and make it more accessible for other contributors to understand.

**Comment by olliestanley** [comment]
Can this be closed now that both #937 and #952 are merged?
