### ISSUE TITLE
Send backend HTTP requests with `x-oasst-user` header 

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#953]
Add a `x-oasst-user: <auth_method>:<username>` whenever possible (when a user is logged in) to all HTTP requests to the backend. Username is the user-id used by the frontend (not to mix with display-name).

**Comment by baddhidurgarao** [comment]
[Buy Github Followers, Stars, Forks & Watchers](https://baddhi.shop/product/buy-github-followers/) from Baddhi Shop

**Comment by hemangjoshi37a** [comment]
@andreaskoepf,

I understand the requirement to add the x-oasst-user header to all HTTP requests to the backend, with the format x-oasst-user: <auth_method>:<username> where username is the user-id used by the frontend.

In addition to implementing this change, I would also suggest adding a check to ensure that the auth_method and username values are properly formatted, and handling any errors that may occur as a result. Additionally, I would recommend adding proper logging to track when the x-oasst-user header is added and its values for debugging and auditing purposes.

I would also suggest that we should mention the related people like @hemangjoshi37a, and also mention the related labels like backend, website so that they can also check it and give suggestions.

Please let me know if this is in line with your expectations and I can proceed to implement these changes.

**Comment by andreaskoepf** [comment]
The backend part is very trivial, I created this issue mainly for the web-team. I think @AbdBarho will take care of it.

**Comment by AbdBarho** [comment]
@andreaskoepf should we add the header to ALL endpoints?

**Comment by andreaskoepf** [comment]
> @andreaskoepf should we add the header to all endpoints, even the ones that did not need user info before?

If you can simply pass on the current logged in user everywhere, then please yes. The user-info is not evaluated everywhere yet .. but it could be used for logging etc to identify on behalf of which frontend-user the calls were made. I created a backend PR https://github.com/LAION-AI/Open-Assistant/pull/957  ...

If if is too cumbersome to do it everywhere than please for now only add it to all message requests.

**Comment by AbdBarho** [comment]
@andreaskoepf I added it everywhere, even if we don't need it now, we can use it generally for rate limiting. #959

**Comment by andreaskoepf** [comment]
@AbdBarho thanks a lot for adapting everything so fast!
