### ISSUE TITLE
Task "Reply as Assistant" says "enter your prompt" in the textbox

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#979]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/858040/215292963-d210598c-5c8e-451f-8f74-2a24e56ff563.png">

**Comment by occupytheweb** [comment]
Hi @yk. I can fix this.
What should the placeholder read? Is "Write your reply here..." fine?

My approach would be to slightly refactor the tasks translation file to something like:
```
  "reply_as_user": {
    ...
    "response_placeholder": "Write your prompt here..."
  },
  "reply_as_assistant": {
    ...
    "response_placeholder": "Write your reply here..."
  },
```
and then delete the now unused top-level `write_initial_prompt` mapping.

Also, should the "Reply as User" task still say "Write your prompt here..." ?

**Comment by occupytheweb** [comment]
Hi @andreaskoepf.
Could you tell me which tasks types have similar placeholders? (I identified `create_initial_prompt`, `reply_as_user` and `reply_as_assistant`, but haven't seen the labelling tasks yet due to unavailability)

Also, should the "Reply as User" task still say "Write your prompt here..." ?

**Comment by othrayte** [comment]
The create task types (the ones you mentioned) are the only tasks with text input.
